### ISSUE TITLE
repos.txt file

### ISSUE THREAD

**Issue by conceptofmind** [sourcegraph/codesearch.ai#3]
Hi,

Is there a file of the list of repositories (repos.txt) available to use for recreating the results in the sourcegraph notebook?

> Once we have initialized our database, we can finally start collecting code and query pairs. We will begin by collecting functions and their docstrings from Git repositories. Before starting, we must define the list of repositories we will process. That list should be in the form of a file with one repository per line in the following format: "code-host.url/org/name", for example, github.com/sourcegraph/sourcegraph. To start processing, you will have to specify the path to the repository list file and the number of parallel workers.

Thank you!

**Comment by xxgj** [comment]
+1
